name: ghcp
description: A powerful, lightweight CLI tool for downloading files and directories from GitHub repositories without cloning. Features intelligent output handling, custom filename support, and direct directory extraction.
version: 1.0.0
repository: https://github.com/aminnez/ghcp
homepage: https://github.com/aminnez/ghcp
documentation: https://github.com/aminnez/ghcp#readme
issue_tracker: https://github.com/aminnez/ghcp/issues

topics:
  - cli
  - github
  - download
  - automation
  - devtools

funding:
  - https://github.com/sponsors/aminnez

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.8.1

dependencies:
  http: ^1.5.0
  interact_cli: ^2.4.0
  path: ^1.9.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
  build_runner: ^2.4.8
  mockito: ^5.5.0

executables:
  ghcp:
